version: '3.8'

services:
  proxy:
    build:
      context: ./nginx
    container_name: proxy
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    env_file:
      - ./nginx/.env


  mysql:
    image: mysql:8.0
    container_name: mysql-container
    env_file:
      - backend/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 15s
      timeout: 10s
      retries: 10

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
