services:
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: proxy_dev
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - nginx_dev_config:/etc/nginx
    restart: always
    depends_on:
      - backend
      - frontend
    networks:
      - dev-network
    env_file:
      - ./nginx/.env

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    env_file:
      - backend/.env
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - dev-network
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 10s
      retries: 10

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis_dev_data:/data

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - backend/.env
    networks:
      - dev-network
    depends_on:
      - mysql
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: https://localhost/api
        VITE_WEBSOCKET_URL: wss://localhost/api/helloworld
    container_name: frontend
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  mysql_dev_data:
  redis_dev_data:
  nginx_dev_config:
