services:
  backend:
    build:
      context: ./backend
    container_name: backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - app-network

  proxy:
    build:
      context: ./nginx
    container_name: proxy
    ports:
      # - "443:443"
      # 만약 HTTP(80)도 노출할 경우 아래 줄 주석 해제
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
