FROM nginx:alpine

RUN apk add --no-cache openssl && \
    mkdir -p /etc/nginx/certs && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/certs/localhost-key.pem \
    -out /etc/nginx/certs/localhost-cert.pem \
    -subj "/C=KR/ST=Seoul/L=Gangnam/O=Dev/OU=IT/CN=localhost"
# Nginx 설정 파일 복사
COPY default.dev.conf /etc/nginx/conf.d/default.conf

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
