jwt:
  secret: your-very-secure-secret-key-that-is-at-least-32-characters
  ACCESS_TOKEN_EXPIRATION: 3600000
  REFRESH_TOKEN_EXPIRATION: 604800000
  TEMP_TOKEN_EXPIRATION: 300000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PosturePro?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: cfb992f8871aa4288acb8e03c741e671
            client-secret: voelBw80wfOu2HkNns44cUZ0RBVgbyTM
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize?prompt=login
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie

