jwt:
  secret: yourVerySecretKeyThatIsAtLeast32Characters

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PosturePro?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: cfb992f8871aa4288acb8e03c741e671  # ??? REST API ?
            client-secret: voelBw80wfOu2HkNns44cUZ0RBVgbyTM  # ??? ????? ???
            client-authentication-method: client_secret_post # ????? ???? POST ??? ??
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao  # ???? URL
            authorization-grant-type: authorization_code  # ?? ?? ?? ??
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize?prompt=login  # ?? ?? ?? URL
            token-uri: https://kauth.kakao.com/oauth/token  # ?? ?? ?? URL
            user-info-uri: https://kapi.kakao.com/v2/user/me  # ??? ?? ?? URL
            user-name-attribute: id  # ??? ?? ??

#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# ?? ??
server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie

